[package]
name = "cielo-rs-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
reqwest-middleware = { version = "0.3.3" }
reqwest-retry = { version = "0.6.1" }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.63"

[dev-dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.39.3", features = ["full"] }
